### ISSUE TITLE
Having trouble tracing error:

### ISSUE THREAD

**Issue by dprockcreative** [StarterSquad/ngseed#30]
[12:40:12] Starting 'karma'...
[12:40:12] 'karma' errored after 10 ms
[12:40:12] TypeError: Object #<Object> has no method 'on'
  at Gulp.gulp.task.config.name (/**_/gulpfile.js:28:8)
  at module.exports (/**_/node_modules/gulp/node_modules/orchestrator/node_modules/execify/lib/runTask.js:36:12)
  at Object.asCallback (/**_/node_modules/gulp/node_modules/orchestrator/node_modules/execify/index.js:16:2)
  at Gulp.Orchestrator._runTask (/**_/node_modules/gulp/node_modules/orchestrator/index.js:270:11)
  at Gulp.Orchestrator._runStep (/**_/node_modules/gulp/node_modules/orchestrator/index.js:211:10)
  at Gulp.Orchestrator.start (/**_/node_modules/gulp/node_modules/orchestrator/index.js:132:8)
  at /usr/local/lib/node_modules/gulp/bin/gulp.js:121:20
  at process._tickDomainCallback (node.js:463:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:906:3

**Comment by dmitryevseev** [comment]
Hi @dprockcreative . Clear question will help you to get an answer quicker. Tell more about how to reproduce it.

**Comment by dmitryevseev** [comment]
Closing this as poor described
