### ISSUE TITLE
gulp protractor: ECONNREFUSED...?

### ISSUE THREAD

**Issue by mpiasta-ca** [StarterSquad/ngseed#35]
Any idea what's going on here...?

```
$ gulp protractor
[14:16:57] Using gulpfile d:\test-week-1\ngseed\Gulpfile.js
[14:16:57] Starting 'protractor'...
Using the selenium server at http://127.0.0.1:4444/wd/hub

d:\my-folder\ng-seed-folder\node_modules\protractor\node_modules\selenium-webdriver\ht
tp\index.js:145
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (d:\my-folder\ng-seed-folder\node_modules\protractor\
node_modules\selenium-webdriver\http\index.js:145:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)
==== async task ====
WebDriver.createSession()
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
[14:16:58] 'protractor' errored after 1.36 s
[14:16:58] Error in plugin 'gulp-protractor'
protractor exited with code 1
```

**Comment by TizianoPerrucci** [comment]
Hi @mpiasta-ca from this line "Error: ECONNREFUSED connect ECONNREFUSED" looks like your webdriver server is not running. 
Are you running it? 
Can you check if anything is listening on port 4444?

**Comment by mpiasta-ca** [comment]
OK, hmm, I guess I missed the webdriver setup instructions. But now I get this (and I've already run `webdriver-manager update --standalone`, says `selenium standalone is up to date`):

```
$ gulp webdriver
[16:28:37] Using gulpfile d:\my-folder\ng-seed-folder\gulpfile.js
[16:28:37] Starting 'webdriver'...
Selenium Standalone is not present. Install with webdriver-manager update --standalone
[16:28:37] 'webdriver' errored after 442 ms
[16:28:37] Error: 1
  at formatError (c:\Users\{users}\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:161:10)
  at Gulp.<anonymous> (c:\Users\{users}\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:187:15)
  at Gulp.EventEmitter.emit (events.js:95:17)
  at Gulp.Orchestrator._emitTaskDone (d:\my-folder\ng-seed-folder\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
  at d:\my-folder\ng-seed-folder\node_modules\gulp\node_modules\orchestrator\index.js:275:23
  at finish (d:\my-folder\ng-seed-folder\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
  at ChildProcess.cb (d:\my-folder\ng-seed-folder\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
  at ChildProcess.g (events.js:180:16)
  at ChildProcess.EventEmitter.emit (events.js:98:17)
  at maybeClose (child_process.js:743:16)
  at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

**Comment by Maqsim** [comment]
@mpiasta-ca Hey. Please, try to start selenium server by `webdriver-manager start`

**Comment by mpiasta-ca** [comment]
Hey @Maqsim, thanks, that works. Does it have to be run manually before running protractor, or can queue that to auto-start somehow in the gulp task?

Right now I have to launch `webdriver-manager start` in a separate console, and it has to stay running, while I run the `gulp protractor` command in another console.

**Comment by Maqsim** [comment]
@mpiasta-ca I do the same.

**Comment by mpiasta-ca** [comment]
@Maqsim OK, yeah I spoke with another developer and he also said it's common practice for using protractor. Great, Thanks!
